# Generated by Django 6.0.5 on 2026-05-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('hotel', 'Hotel'), ('homestay', 'Homestay'), ('trekking', 'Trekking'), ('travel', 'Travel'), ('cafe', 'Cafe'), ('wellness', 'Wellness'), ('event', 'Event'), ('home', 'Home Service'), ('local', 'Local Service')], default='local', max_length=30)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('pricing_unit', models.CharField(default='booking', max_length=40)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('deposit_percent', models.PositiveIntegerField(default=30)),
                ('instant_booking_enabled', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.providerprofile')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='services.servicelisting')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=180)),
                ('capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='services.servicelisting')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('url', models.URLField(max_length=700)),
                ('thumbnail_url', models.URLField(blank=True, max_length=700)),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services.servicelisting')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['active', 'service_type'], name='services_se_active_2af88c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['category', 'active'], name='services_se_categor_6721cc_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['base_price'], name='services_se_base_pr_1d68a2_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelisting',
            index=models.Index(fields=['rating_average'], name='services_se_rating__a16db9_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicelisting',
            constraint=models.UniqueConstraint(fields=('provider', 'slug'), name='unique_service_slug_per_provider'),
        ),
        migrations.AddIndex(
            model_name='availabilityblock',
            index=models.Index(fields=['service', 'start_at', 'end_at'], name='services_av_service_02ffbf_idx'),
        ),
    ]
